theme = "lynx"
title = "Atletiekunie.TV"
languageCode = "nl-nl"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Atletiekunie.tv"
  image = "logo-au.jpg"
  links = [
        {youtube = { href = "https://youtube.com/live/t5aPrCtjJrI", text = "ASICS NK Atletiek 2025 - Dag 1"} },
        {youtube = { href = "https://youtube.com/live/MzL0pW5bRqk", text = "ASICS NK Atletiek 2025 - Dag 1 - Geen Commentaar"} },
        {youtube = { href = "https://youtube.com/live/aXiEXLUFxe8", text = "ASICS NK Atletiek 2025 - Dag 2"} },
        {youtube = { href = "https://youtube.com/live/pBAOONBYjnc", text = "ASICS NK Atletiek 2025 - Dag 2 - Geen Commentaar"} },
        {youtube = { href = "https://www.youtube.com/@AtletiekunieTV/streams", text = "AtletiekunieTV Archief"} },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
