theme = "lynx"
title = "Atletiekunie.TV"
languageCode = "nl-nl"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Atletiekunie.tv"
  image = "logo-au.jpg"
  links = [
        {youtube = { href = "https://youtube.com/live/0BI7ypZ0WWY", text = "Warandeloop 2025 - Zaterdag"} },
        {youtube = { href = "https://youtube.com/live/fFjlFXF4fmw", text = "Warandeloop 2025 - Zondag"} },
        {youtube = { href = "https://youtube.com/live/0cN_Jj3--AM", text = "Warandeloop 2025 - Zondag - Geen Commentaar"} },
        {youtube = { href = "https://youtube.com/live/Wi6qwE10cuM", text = "EA Stream"} },
        {youtube = { href = "https://www.youtube.com/@AtletiekunieTV/streams", text = "AtletiekunieTV Archief"} },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
